---
title: "About"
draft: true
---

<h2>Education</h2>

<p class="darkgreen-text">**University of California, Santa Barbara (2026),** Master of Environmental Data Science</p>

Group Capstone Project: TBD

<p class="darkgreen-text">**Wesleyan University (2025),** Bachelor of Arts in Earth & Environmental Sciences, Economics</p>

Group Capstone Project: "Ants, Plants, and Isotopes: Investigating the Trophic Levels of Guanica Dry Forest"

Relevant Coursework: Soils, Sedimentology, Renewable Energy, Environmental and Resource Economics

<h2>Study Abroad</h2>

<p class="darkgreen-text">**University of Otago (Fall 2024)**</p>

Courses:

<p class="darkgreen-text">**La Universidad del San Francisco de Quito (January 2024)**</p>

Course:

<h2>Research and Professional Experience</h2>

<h3>About Me</h3>

I grew up in southern Connecticut, and ended up at Wesleyan University for my undergraduate education. I double-majored in Earth & Environmnetal Sciences and Economics, and am continuously surprised at how interconnected the two fields are. 

Some of my past projects include exploring evolutionary divergence of fish species, trophic levels of ants in Puerto Rico, and testing for bacteria concentrations at a water quality monitoring organization.

In my free time, I enjoy hiking, swimming, reading, and doing little crafts like crocheting and sewing. I'm also a big fan of the Great British Baking Show and Bad Bunny. Current personal projects include practicing my Spanish (I traveled to Argentina this winter and was able to get around!) and potentially running another half marathon soon.