{
  "hash": "f28c75f092df2a34b429b1371a0c2a8e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Do Sea‑Level Rise Maps Backfire?\"\nsubtitle: \"Using a randomized experiment to prove causality in the San Francisco Bay Area\"\nauthor: \n- name: \"Joshua Ferrer-Lozano\"\n- name: \"Zach Loo\"\n- name: \"William Mullins\"\n- name: \"Sofia Sarak\"\ndate: \"March 19, 2026\"\nformat: html\neditor: visual\n---\n\n\n::: {.cell layout-ncol=\"1\"}\n::: {.cell-output-display}\n![Flooding in the Bay Area is particularly intense when rainstorms coincide with king tides (Source: The San Fransisco Chronicle, 2025).](images/sf_flooding.jpg){width=80%}\n:::\n:::\n\n\nThe following blog post breaks down the use of a randomized experiment and replicates the methods and code (using the original data) from a published study. Navigate to the appropriate sections for the following:\n\n**Background:** A brief overview of the study we are replicating.\n\n**Study Design:**\n\n-   Explanation of the randomized experiment\n\n-   Survey methods\n\n-   Outcome variable\n\n-   Running variable\n\n-   Causal Identification Strategy\n\n**Recreation of Results/Figure 4:** Our version of the study's methods and code, using only a subset of the data.\n\n**Interpretation and Conclusion:**\n\n-   3 major takeaways\n\n-   Causal identification\n\n-   Statistical assumptions\n\n-   Sampling and External Validity\n\n-   Outcome validity concerns\n\nA full exploration of the study and the accompanying code can be found in our [GitHub repository](https://github.com/sofiasarak/slr-random-experiment-sf).\n\n## Background\n\nSea‑level rise (SLR) is one of California’s most pressing climate risks. Yet even in a climate‑aware state, public concern about SLR remains surprisingly low. [Mildenberger et al. (2024)](https://www.nature.com/articles/s41893-024-01380-0) test whether personalized SLR maps increase resident concern by showing how rising seas could affect their home.\n\nThe surprising finding: maps often reduce perceived personal harm, even for people whose homes are projected to flood.\n\nThis blog post walks through the design‑based causal method of a randomized experiment to recreate the California‑only version of Figure 4, which shows how the map’s treatment effect varies with distance from the SLR boundary. The original study conducted this analysis on coastal communities of New Jersey, Florida, and Virginia, as well. California data comes from the San Francisco Bay Area.\n\n::: {#fig-4}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/figure4.png){fig-align='center' width=70%}\n:::\n:::\n\n\nEffect of map treatment on personal concern, with separate regressions estimated at 50 meter intervals, pooled across California, New Jersey, Virginia and Florida samples (Mildenberger et al. 2024, Figure 4).\n:::\n\nWe opted to conduct the replication using data from only one state in order to explore whether study findings hold even when considering just a subset, as well as limit our scope to allow for a more in-depth analysis of the causal method itself. Additionally, we chose California because provides the cleanest replication of Figure 4 due to consistent geospatial data availability and a larger sample size within a single region.\n\n# Study Design\n\n------------------------------------------------------------------------\n\n## Randomized experiment\n\nRespondents in California were recruited using address‑level mail‑to‑web sampling. Each respondent was randomly assigned to:\n\n**Treatment (treat_map = 1):** See a customized SLR map centered on their home\n\n**Control (treat_map = 0):** See no map\n\nBecause treatment is randomized, the difference in outcomes between treated and control respondents is meant to be a causal estimate of the map’s effect.\n\nAdditionally, the study utilized a geographic risk discontinuity design to test whether there was a difference in concern between respondents that were just within or just outside of the flood zone. Under these assumptions, these residents should be relatively similar in most covariates other than the risk to sea level rise. A jump in concern between groups on either side of the threshold would indicate a treatment effect.\n\n### Survey Methods\n\nIndividualized letters were sent to households within the sample area (San Francisco Bay, CA) in Fall 2020; the timing of survey completion depended on when respondents chose to complete it. The average response rates inside and outside the projected SLR boundary (as a fraction of mailed invitations) -- of all 4 states in the original study -- was 2.6% and 3.1% respectively. Treatment, or whether the letter/survey was accompanied by a map of SLR, was randomized using the Qualtric web platform.\n\nAlthough the randomization assumption was met in this case, the low rate of response has the potential to contribute non-response/participation bias in the outcome.\n\n## Outcome variable\n\n`dv_personal` — The study measures perceived risk or personal harm from SLR using a 0-3 scale, which respondents selected in their surveys.\n\n## Running variable\n\nTo recreate Figure 4, we use:\n\n`dist_min` — distance (in meters) from the SLR boundary, where negative values correspond to homes inside the projected flood zone and positive ones outside of it.\n\nThis running variable is used to estimate spatial heterogeneity in the treatment effect.\n\n## Causal Identification Strategy\n\nThe randomized sample estimates an Average Treatment Effect (ATE). Because map exposure is randomly assigned, the causal effect is simply:\n\n::: {style=\"font-size: 0.8em; text-align: center;\"}\n**ATE = mean outcome of those that received the SLR map - mean outcome of those that did not receive map**\n:::\n\nSpatial heterogeneity/geographic risk discontinuity (Figure 4) is leveraged to understand whether the map works differently for people closer to the flood zone. The study does the following:\n\n1.  Bin respondents into 50‑meter intervals of distance to the SLR boundary\n\n2.  Estimate the treatment effect within each bin\n\n3.  Plot those bin‑specific effects against distance\n\nTo reiterate, this is not a formal regression discontinuity design, but it borrows the intuition that if the map increases personal relevance, the treatment effect should be strongest near the boundary.\n\n## Study Result\n\nThe treatment effect is negative (reduces concern of SLR risk), regardless of geographic location. Across all four states, the authors find that personalized SLR maps reduce perceived personal harm. Respondents shown a map report significantly lower concern than those in the control group, even when their homes are explicitly shown inside the projected flood zone. This counterintuitive “backfire effect” is one of the central findings of the study.\n\n# Recreation of Results/Figure 4\n\nThe following section contains code that estimates the Average Treatment Effect using the randomized experiment data. It also prepares the data necessary to recreate Figure 4, or the geographic risk discontinuity, and plots it.\n\n------------------------------------------------------------------------\n\n## Load Required Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(estimatr)\nlibrary(gtsummary)\n```\n:::\n\n\n## Load and Clean California Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CA survey data\ndata_ca <- read_csv(here(\"blog\", \"slr-random-experiment-sf\",\"data\", \"SeaLevelRiseSurvey_California_January+16,+2021_13.54.csv\")) %>%\n  .[-c(1,2),] %>%\n  mutate(geo = \"CA\")\n\n# Load CA distance-to-boundary file\ndist_ca <- read_csv(here(\"blog\", \"slr-random-experiment-sf\",\"data\", \"ca_dist_mins.csv\"))\n\n# Load CA combined metadata\ncw_ca <- read_csv(here(\"blog\", \"slr-random-experiment-sf\",\"data\", \"ca_combined_final_withtraffic_sub.csv\"))\n\n# Load flood zone file\nfld_zone <- read.csv(here(\"blog\", \"slr-random-experiment-sf\", \"data\", \"fld_zone.csv\"))\n```\n:::\n\n\n## Merge Survey, Distance and Flood Zone\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_ca_clean <- dist_ca %>% \n  # Keep only the first occurrence\n  filter(!duplicated(.)) %>%\n  group_by(adds) %>%\n  # Filter to minimum at each address\n  filter(dist_min == min(dist_min)) %>%\n    inner_join(cw_ca %>%  # Join traffic data on addresses, and retain corresponding emails and IDS\n      select(adds, email, FID) %>% \n      filter(!duplicated(.))) %>%\n  rename(RecipientEmail = email) %>%\n  inner_join(fld_zone %>% # Join flood zone info on addresses, keeping county, tract, and flood zone info\n             select(adds, COUNTYFP, TRACTCE, FLD_ZONE) %>% \n             distinct(adds, .keep_all = TRUE))\n```\n:::\n\n\nIn the analysis we are replicating in this blog post, traffic data is not used (but it used for another experiment in the same study, which is why it is included here).\n\n**Data Description:** This intermediary clean data frame contains the following columns:\n\n-   `adds` - Residential addresses where surveys were sent\n\n-   `dist_min` - The minimum distance to the SLR boundary\n\n-   `RecipientEmail` - Email address associated with recipient of survey\n\n-   `FID` - Feature IDs from the corresponding geospatial data set\n\n-   `COUNTYFP` - County identifier (there are 10 unique counties included in this study)\n\n-   `TRACTCE` - Census tract identifier\n\n-   `FLD_ZONE` - Flood zone area identifier\n\n## Construct California-Only Analytic Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create function that recodes survey responses to numeric values\ndv_recode <- function(x){\n  case_when(\n    x == \"Not at all\" ~ 0,\n    x == \"Only a little\" ~ 1,\n    x == \"A moderate amount\" ~ 2,\n    x == \"A great deal\" ~ 3\n  )\n}\n\n# Clean CA data frame\ndata_ca_clean <- data_ca %>%\n  # Join with cleaned distance data, by email\n  left_join(dist_ca_clean, by = \"RecipientEmail\") %>%\n    \n  mutate(\n    # Boolean variable denoting whether observation received a map treatment\n    treat_map = !is.na(exp_emphasis),\n    \n    # Boolean variable denoting whether the image shown was a SLR image\n    slr = str_detect(img, \"SLR\"),\n    \n    # Recode survey responses using function made above\n    dv_personal = dv_recode(slharmpersonal),\n    \n    # Flip sign of dist_min so that negative values represent closer to coast/greater risk\n    dist_min = ifelse(slr == TRUE, -dist_min, dist_min)\n  ) %>%\n  \n  # Remove NA values\n  filter(!is.na(dv_personal), !is.na(dist_min))\n```\n:::\n\n\n## California-Only Covariate Balance Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create balance table comparing groups that did and did not receive treatment\ndata_ca_clean |> \n  select(race, edu, gender, ideo, party, dist_min, treat_map) |> \n  tbl_summary(\n    by = treat_map,\n    statistic = list(all_continuous() ~ \"{mean} ({sd})\")) |> \n  modify_header(label ~\"**Covariate**\") |> \n  modify_spanning_header(c(\"stat_1\", \"stat_2\") ~ \"**Map Treatment**\") |> \n  as_gt() |> \n  gt::opt_interactive(use_compact_mode = TRUE) # Reduce long balance table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ddelyivqss\" class=\".gt_table\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ddelyivqss table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ddelyivqss thead, #ddelyivqss tbody, #ddelyivqss tfoot, #ddelyivqss tr, #ddelyivqss td, #ddelyivqss th {\n  border-style: none;\n}\n\n#ddelyivqss p {\n  margin: 0;\n  padding: 0;\n}\n\n#ddelyivqss .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ddelyivqss .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ddelyivqss .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ddelyivqss .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ddelyivqss .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ddelyivqss .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ddelyivqss .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ddelyivqss .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ddelyivqss .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ddelyivqss .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ddelyivqss .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ddelyivqss .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ddelyivqss .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ddelyivqss .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ddelyivqss .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ddelyivqss .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ddelyivqss .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ddelyivqss .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ddelyivqss .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ddelyivqss .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ddelyivqss .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ddelyivqss .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ddelyivqss .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ddelyivqss .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ddelyivqss .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ddelyivqss .gt_left {\n  text-align: left;\n}\n\n#ddelyivqss .gt_center {\n  text-align: center;\n}\n\n#ddelyivqss .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ddelyivqss .gt_font_normal {\n  font-weight: normal;\n}\n\n#ddelyivqss .gt_font_bold {\n  font-weight: bold;\n}\n\n#ddelyivqss .gt_font_italic {\n  font-style: italic;\n}\n\n#ddelyivqss .gt_super {\n  font-size: 65%;\n}\n\n#ddelyivqss .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ddelyivqss .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ddelyivqss .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ddelyivqss .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ddelyivqss .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ddelyivqss .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ddelyivqss .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ddelyivqss .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ddelyivqss div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<div id=\"ddelyivqss\" class=\"reactable html-widget\" style=\"width:auto;height:auto;\"></div>\n<div style=\"font-family:system-ui, &#39;Segoe UI&#39;, Roboto, Helvetica, Arial, sans-serif;border-top-style:solid;border-top-width:2px;border-top-color:#D3D3D3;border-bottom-style:solid;border-bottom-width:2px;border-bottom-color:#D3D3D3;padding-top:6px;padding-bottom:6px;padding-left:10px;padding-right:10px;\">\n<div></div>\n<div>\n<div class=\"gt_footnotes\">\n<div class=\"gt_footnote\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"biAoJSk7IE1lYW4gKFNEKQ==\"><span class='gt_from_md'>n (%); Mean (SD)</span></span></div>\n</div>\n</div>\n</div>\n<script type=\"application/json\" data-for=\"ddelyivqss\">{\"x\":{\"tag\":{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"label\":[\"race\",\"African American\",\"African American,Native American\",\"African American,Pacific Islander\",\"Asian\",\"Asian,Pacific Islander\",\"Asian,Pacific Islander,Other\",\"Hispanic\",\"Hispanic,Native American\",\"Native American\",\"Other\",\"Pacific Islander\",\"White/Caucasian\",\"White/Caucasian,African American\",\"White/Caucasian,African American,Hispanic,Asian,Native American,Pacific Islander,Other\",\"White/Caucasian,Asian\",\"White/Caucasian,Hispanic\",\"White/Caucasian,Hispanic,Asian\",\"White/Caucasian,Native American\",\"White/Caucasian,Other\",\"Unknown\",\"edu\",\"2-year College Degree\",\"4-year College Degree\",\"Doctoral Degree\",\"High School / GED\",\"Less than High School\",\"Masters Degree\",\"Professional Degree (JD, MD)\",\"Some college\",\"Trade school\",\"Unknown\",\"gender\",\"Female\",\"Male\",\"Unknown\",\"ideo\",\"Conservative\",\"Extremely conservative\",\"Extremely liberal\",\"Liberal\",\"Moderate; middle of the road\",\"Slightly conservative\",\"Slightly liberal\",\"Unknown\",\"party\",\"Democrat\",\"Independent\",\"Other Party\",\"Republican\",\"Unknown\",\"dist_min\"],\"stat_1\":[null,\"7 (2.1%)\",\"1 (0.3%)\",\"0 (0%)\",\"82 (25%)\",\"1 (0.3%)\",\"0 (0%)\",\"18 (5.5%)\",\"0 (0%)\",\"0 (0%)\",\"9 (2.8%)\",\"2 (0.6%)\",\"188 (58%)\",\"2 (0.6%)\",\"0 (0%)\",\"1 (0.3%)\",\"8 (2.5%)\",\"2 (0.6%)\",\"4 (1.2%)\",\"1 (0.3%)\",\"30\",null,\"20 (6.1%)\",\"115 (35%)\",\"23 (7.1%)\",\"5 (1.5%)\",\"4 (1.2%)\",\"108 (33%)\",\"20 (6.1%)\",\"30 (9.2%)\",\"1 (0.3%)\",\"30\",null,\"116 (36%)\",\"208 (64%)\",\"32\",null,\"22 (6.8%)\",\"2 (0.6%)\",\"16 (4.9%)\",\"101 (31%)\",\"89 (27%)\",\"29 (8.9%)\",\"66 (20%)\",\"31\",null,\"186 (57%)\",\"83 (26%)\",\"26 (8.0%)\",\"30 (9.2%)\",\"31\",\"407 (737)\"],\"stat_2\":[null,\"3 (1.0%)\",\"0 (0%)\",\"1 (0.3%)\",\"89 (29%)\",\"0 (0%)\",\"1 (0.3%)\",\"10 (3.3%)\",\"1 (0.3%)\",\"1 (0.3%)\",\"11 (3.6%)\",\"0 (0%)\",\"169 (56%)\",\"3 (1.0%)\",\"1 (0.3%)\",\"4 (1.3%)\",\"6 (2.0%)\",\"1 (0.3%)\",\"1 (0.3%)\",\"0 (0%)\",\"22\",null,\"15 (4.9%)\",\"98 (32%)\",\"35 (12%)\",\"10 (3.3%)\",\"0 (0%)\",\"92 (30%)\",\"27 (8.9%)\",\"25 (8.2%)\",\"2 (0.7%)\",\"20\",null,\"131 (43%)\",\"172 (57%)\",\"21\",null,\"18 (5.9%)\",\"2 (0.7%)\",\"19 (6.3%)\",\"105 (35%)\",\"86 (28%)\",\"18 (5.9%)\",\"56 (18%)\",\"20\",null,\"183 (60%)\",\"79 (26%)\",\"17 (5.6%)\",\"24 (7.9%)\",\"21\",\"335 (759)\"]},\"columns\":[{\"id\":\"label\",\"name\":\"<span data-qmd-base64=\\\"KipDb3ZhcmlhdGUqKg==\\\"><span class='gt_from_md'><strong>Covariate<\\/strong><\\/span><\\/span>\",\"type\":\"character\",\"na\":\"NA\",\"minWidth\":125,\"style\":\"function(rowInfo, colInfo) {\\nconst rowIndex = rowInfo.index + 1\\n}\",\"cell\":[\"race\",\"    African American\",\"    African American,Native American\",\"    African American,Pacific Islander\",\"    Asian\",\"    Asian,Pacific Islander\",\"    Asian,Pacific Islander,Other\",\"    Hispanic\",\"    Hispanic,Native American\",\"    Native American\",\"    Other\",\"    Pacific Islander\",\"    White/Caucasian\",\"    White/Caucasian,African American\",\"    White/Caucasian,African American,Hispanic,Asian,Native American,Pacific Islander,Other\",\"    White/Caucasian,Asian\",\"    White/Caucasian,Hispanic\",\"    White/Caucasian,Hispanic,Asian\",\"    White/Caucasian,Native American\",\"    White/Caucasian,Other\",\"    Unknown\",\"edu\",\"    2-year College Degree\",\"    4-year College Degree\",\"    Doctoral Degree\",\"    High School / GED\",\"    Less than High School\",\"    Masters Degree\",\"    Professional Degree (JD, MD)\",\"    Some college\",\"    Trade school\",\"    Unknown\",\"gender\",\"    Female\",\"    Male\",\"    Unknown\",\"ideo\",\"    Conservative\",\"    Extremely conservative\",\"    Extremely liberal\",\"    Liberal\",\"    Moderate; middle of the road\",\"    Slightly conservative\",\"    Slightly liberal\",\"    Unknown\",\"party\",\"    Democrat\",\"    Independent\",\"    Other Party\",\"    Republican\",\"    Unknown\",\"dist_min\"],\"html\":true,\"align\":\"left\"},{\"id\":\"stat_1\",\"name\":\"<span data-qmd-base64=\\\"KipGQUxTRSoqICAKTiA9IDM1Ng==\\\"><span class='gt_from_md'><strong>FALSE<\\/strong><br />\\nN = 356<\\/span><\\/span><span class=\\\"gt_footnote_marks\\\" style=\\\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\\\"><sup>1<\\/sup><\\/span>\",\"type\":\"character\",\"na\":\"NA\",\"minWidth\":125,\"style\":\"function(rowInfo, colInfo) {\\nconst rowIndex = rowInfo.index + 1\\n}\",\"cell\":[\"<br />\",\"7 (2.1%)\",\"1 (0.3%)\",\"0 (0%)\",\"82 (25%)\",\"1 (0.3%)\",\"0 (0%)\",\"18 (5.5%)\",\"0 (0%)\",\"0 (0%)\",\"9 (2.8%)\",\"2 (0.6%)\",\"188 (58%)\",\"2 (0.6%)\",\"0 (0%)\",\"1 (0.3%)\",\"8 (2.5%)\",\"2 (0.6%)\",\"4 (1.2%)\",\"1 (0.3%)\",\"30\",\"<br />\",\"20 (6.1%)\",\"115 (35%)\",\"23 (7.1%)\",\"5 (1.5%)\",\"4 (1.2%)\",\"108 (33%)\",\"20 (6.1%)\",\"30 (9.2%)\",\"1 (0.3%)\",\"30\",\"<br />\",\"116 (36%)\",\"208 (64%)\",\"32\",\"<br />\",\"22 (6.8%)\",\"2 (0.6%)\",\"16 (4.9%)\",\"101 (31%)\",\"89 (27%)\",\"29 (8.9%)\",\"66 (20%)\",\"31\",\"<br />\",\"186 (57%)\",\"83 (26%)\",\"26 (8.0%)\",\"30 (9.2%)\",\"31\",\"407 (737)\"],\"html\":true,\"align\":\"center\"},{\"id\":\"stat_2\",\"name\":\"<span data-qmd-base64=\\\"KipUUlVFKiogIApOID0gMzI0\\\"><span class='gt_from_md'><strong>TRUE<\\/strong><br />\\nN = 324<\\/span><\\/span><span class=\\\"gt_footnote_marks\\\" style=\\\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\\\"><sup>1<\\/sup><\\/span>\",\"type\":\"character\",\"na\":\"NA\",\"minWidth\":125,\"style\":\"function(rowInfo, colInfo) {\\nconst rowIndex = rowInfo.index + 1\\n}\",\"cell\":[\"<br />\",\"3 (1.0%)\",\"0 (0%)\",\"1 (0.3%)\",\"89 (29%)\",\"0 (0%)\",\"1 (0.3%)\",\"10 (3.3%)\",\"1 (0.3%)\",\"1 (0.3%)\",\"11 (3.6%)\",\"0 (0%)\",\"169 (56%)\",\"3 (1.0%)\",\"1 (0.3%)\",\"4 (1.3%)\",\"6 (2.0%)\",\"1 (0.3%)\",\"1 (0.3%)\",\"0 (0%)\",\"22\",\"<br />\",\"15 (4.9%)\",\"98 (32%)\",\"35 (12%)\",\"10 (3.3%)\",\"0 (0%)\",\"92 (30%)\",\"27 (8.9%)\",\"25 (8.2%)\",\"2 (0.7%)\",\"20\",\"<br />\",\"131 (43%)\",\"172 (57%)\",\"21\",\"<br />\",\"18 (5.9%)\",\"2 (0.7%)\",\"19 (6.3%)\",\"105 (35%)\",\"86 (28%)\",\"18 (5.9%)\",\"56 (18%)\",\"20\",\"<br />\",\"183 (60%)\",\"79 (26%)\",\"17 (5.6%)\",\"24 (7.9%)\",\"21\",\"335 (759)\"],\"html\":true,\"align\":\"center\"}],\"columnGroups\":[{\"name\":\"**Map Treatment**\",\"header\":\"<span data-qmd-base64=\\\"KipNYXAgVHJlYXRtZW50Kio=\\\"><span class='gt_from_md'><strong>Map Treatment<\\/strong><\\/span><\\/span>\",\"html\":true,\"headerStyle\":{\"fontWeight\":\"normal\",\"backgroundColor\":\"transparent\",\"borderBottomStyle\":\"solid\",\"borderBottomWidth\":\"2px\",\"borderBottomColor\":\"#D3D3D3\",\"borderLeftStyle\":\"solid\",\"borderLeftWidth\":\"4px\",\"borderLeftColor\":\"transparent\",\"borderRightStyle\":\"solid\",\"borderRightWidth\":\"4px\",\"borderRightColor\":\"transparent\"},\"columns\":[\"stat_1\",\"stat_2\"]}],\"defaultPageSize\":10,\"showPageSizeOptions\":false,\"pageSizeOptions\":[10,25,50,100],\"paginationType\":\"numbers\",\"showPagination\":true,\"showPageInfo\":true,\"minRows\":1,\"compact\":true,\"height\":\"auto\",\"theme\":{\"color\":\"#333333\",\"backgroundColor\":\"#FFFFFF\",\"stripedColor\":\"rgba(128,128,128,0.05)\",\"style\":{\"font-family\":\"system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif\",\"fontSize\":\"16px\"},\"tableStyle\":{\"borderTopStyle\":\"solid\",\"borderTopWidth\":\"2px\",\"borderTopColor\":\"#D3D3D3\"},\"headerStyle\":{\"fontWeight\":\"normal\",\"backgroundColor\":\"transparent\",\"borderBottomStyle\":\"solid\",\"borderBottomWidth\":\"2px\",\"borderBottomColor\":\"#D3D3D3\"},\"groupHeaderStyle\":{\"fontWeight\":\"normal\",\"backgroundColor\":\"transparent\",\"borderBottomStyle\":\"solid\",\"borderBottomWidth\":\"2px\",\"borderBottomColor\":\"#D3D3D3\"},\"cellStyle\":{\"fontWeight\":\"normal\"}},\"elementId\":\"ddelyivqss\",\"dataKey\":\"f9353cc0df735c7d4e5a98933cc470ae\"},\"children\":[]},\"class\":\"reactR_markup\"},\"evals\":[\"tag.attribs.columns.0.style\",\"tag.attribs.columns.1.style\",\"tag.attribs.columns.2.style\"],\"jsHooks\":[]}</script>\n</div>\n```\n\n:::\n:::\n\n\n**Covariate Summary**: The covariate balance table compares demographic and geographic features between respondents who received the SLR map treatment and those who did not. Across covariates like race, gender, distance from SLR boundary, etc., the distributions are similar between groups, indicating successful randomization. This balance is essential for this study's causal identification strategy as `dv_personal` can be attributed to the map itself rather than underlying differences between respondents.\n\n**Data Description:** The final clean data frame contains a total of 123 columns, we will not summarize in entirety here. Those that are necessary for our analysis include:\n\n-   `dv_personal`: Survey result, recoded as 0-3 to represent responses \"Not at all\", \"Only a little\", \"A moderate amount\", and \"A great deal\", respectively, when residents were asked about SLR concern. This is our **outcome variable**.\n-   `treat_map`: Whether treatment was applied (SLR map included in survey). This is our **treatment variable**.\n-   `dist_min`: Minimum distance (in meters) to SLR boundary. This is the **running variable** for our spatial heterogeneity test.\n\nThis data contains 680 observations from California residents. The entire dataset (not used here) containing data from all four states has a sample size of 1,243\n\nIn the following steps, we replicate two components of the study:\n\n1)  The **Average Treatment Effect (ATE)** of map exposure on perceived personal harm, and\n2)  The **spatial heterogeneity analysis** used to construct Figure 4.\n\n## Step 1 - Estimate the ATE of California\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run robust linear model, using personal risk as response and map treatment as predictor\nmod_ate <- lm_robust(dv_personal ~ treat_map, se_type = \"HC1\", \n                     data = data_ca_clean)\n\n# Print summary\nsummary(mod_ate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm_robust(formula = dv_personal ~ treat_map, data = data_ca_clean, \n    se_type = \"HC1\")\n\nStandard error type:  HC1 \n\nCoefficients:\n              Estimate Std. Error t value   Pr(>|t|) CI Lower CI Upper  DF\n(Intercept)     1.5646    0.04869  32.137 2.129e-138   1.4690   1.6602 678\ntreat_mapTRUE  -0.2529    0.07454  -3.392  7.332e-04  -0.3992  -0.1065 678\n\nMultiple R-squared:  0.01685 ,\tAdjusted R-squared:  0.0154 \nF-statistic: 11.51 on 1 and 678 DF,  p-value: 0.0007332\n```\n\n\n:::\n:::\n\n\nThe above code chunk conducts a simple linear regression of `dv_personal` on `treat_map`, which is estimated using `lm_robust()` with HC1 (heteroskedasticity-consistent) standard errors. This results in an estimate of the average treatment effect of seeing the map on perceived personal harm.\n\nThis identification approach is a simple difference in means under randomization, meaning that no covariates , fixed effects, or matching are used. The intercept reported by the model is 1.565 (p \\< 0.001), representing the mean level of perceived personal harm among control-group respondents. As this is on a 0-3 scale, this indicates a moderate baseline level of concern. The treatment coefficient is −0.253 (SE = 0.075, p = 0.0007), meaning that respondents who saw the personalized SLR map reported roughly a quarter of a point less personal concern than those who did not. The 95% confidence interval excludes zero, which indicates that the map causally reduces perceived personal harm\n\n## Step 2 — Create distance bins\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set bin width\nbin_width <- 50\n\n# Create data set where each observation is binned based on distance away from SLR line\ndata_ca_binned <- data_ca_clean %>%\n  mutate(\n    dist_bin = bin_width * round(dist_min / bin_width),\n    dist_bin = pmax(pmin(dist_bin, 500), -500)\n  )\n```\n:::\n\n\nThe above code discretizes the dist_min variable into 50 meter bins by rounding to the nearest multiple of 50. Bins are capped at +- 500 meters, meaning that all observations more than 500 meters from the SLR boundary are lumped together into “extreme” bins.\n\n## Step 3 - Estimate treatment effect within each bin\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffects_ca <- data_ca_binned %>%\n  \n  # Keep only distance bins that are more than 15 meters away from SLR line/flood zone\n  group_by(dist_bin) %>%\n  filter(n() >= 15) %>%\n  \n  # Run same model as before\n  do(tidy(lm_robust(\n    dv_personal ~ treat_map,\n    se_type = \"HC1\",\n    data = .\n  ))) %>%\n  \n  # Ungroup\n  ungroup() %>%\n  \n  # Keep only observations that received treatment\n  filter(term == \"treat_mapTRUE\") %>%\n  \n  # Calculate confidnece intervals\n  mutate(\n    ci_low = estimate - 1.96 * std.error,\n    ci_high = estimate + 1.96 * std.error\n  )\n```\n:::\n\n\nThe above code conducts a separate OLS regression of `dv_personal` on `treat_map` with HC1 standard errors for each of the bins. Bins with less than 15 observations are dropped to reduce noise. This should, in theory, test the impact of the map based on the flood zone. For this to work, randomization must be maintained across each bin.\n\n## Step 4 - Plot California - Only Figure\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Replicate Figure 4, only with SF Bay Area data\nggplot(effects_ca, aes(x = dist_bin, y = estimate)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  geom_vline(xintercept = 0, linetype = \"dashed\") +\n  geom_point(size = 2) +\n  geom_errorbar(aes(ymin = ci_low, ymax = ci_high), width = 20, alpha = 0.6) +\n  geom_smooth(method = \"loess\", se = TRUE, color = \"red\") +\n  theme_minimal() +\n  labs(\n    title = \"Outcome: Sense of personal harm (California only)\",\n    subtitle = \"Treatment effect of map by distance from SLR boundary\",\n    x = \"Distance from SLR boundary (negative = inside SLR zone)\",\n    y = \"Treatment effect of map\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nThe above code produces a scatter plot of bin specific treatment effects (y-axis) against the distance from the SLR boundary (x-axis). The plot shows regardless of the distance from the SLR boundary, the effect of the treatment often trended negative even in the “extreme” group. This indicates that the survey may have backfired, as many people likely to be impacted seem to report feeling less perceived personal harm.\n\n# Interpretation\n\n------------------------------------------------------------------------\n\nThree key insights emerge from the California analysis:\n\n1.  **Maps reduce perceived personal harm across almost all distances.** Even respondents whose homes are projected to flood show lower concern after seeing the map.\n\n2.  **There is no sharp change at the SLR boundary.** If maps increased personal relevance, we would expect a spike near 0 meters. Instead, the curve is flat and negative.\n\n3.  **California behaves like the national sample.** Despite higher climate awareness, the backfire effect persists. This insight is based on evidence from the original study, as well. The national sample is in reference to the first experiment that consisted of a sample of four coastal regions in the states of California, Florida, New Jersey and Virginia.\n\n::: {#fig-compare}\n\n::: {.cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![](images/figure4.png){width=463}\n:::\n\n::: {.cell-output-display}\n![](images/figure4.png){width=463}\n:::\n:::\n\n\nComparing Mildenberger et al. (2024)'s results (left) to ours (right) reveals that inside the flood zone (negative distances), California's treatment effect paralleled that of the entire study sample. We can also see that outside of the flood zone (positive distances), Californians' sense of personal harm either didn't change or increased, whereas the backfire effect was stronger in the four-state sample.\n:::\n\n**Backfire Effect**: The negative treatment effect across most of the distances that indicates that maps may unintentionally make respondents less concerned about sea-level rise. Even respondents with homes projected to flood showed reduced perceived harm after viewing the map.\n\n# Conclusion and Summary\n\nThis study utilizes a randomized experiment to produce causal inference results. Additionally, spatial heterogeneity allows for mechanism exploration. However, due to the survey methodology, non-response bias persists.\n\nFor policymakers, the takeaway is clear: SLR maps may unintentionally reduce concern, even among at‑risk households.\n\n**Causal Identification:**\n\n-   The study's identification strategy is a randomized survey experiment that provides credibility.\n\n-   In the California sample, the treatment assignment (treat_map) is independent of respondent characteristics because the map is randomly shown after the individuals enter the survey.\n\n-   For ATE and bin-level estimates in Figure 4, the causal effect can be identified if: Randomization was implemented correctly If one respondent's treatment does not affect anther's outcome (SUTVA) This leads to the belief that internal validity is strong and that the randomized design credibly identifies the short-run causal effect of seeing the map on the survey outcome.\n\n**Spatial Analysis Assumptions**: The spatial heterogeneity analysis assumes the following: - Randomization holds within each distance. - Treatment effects are comparable across bins. - Distance to the SLR boundary is measured without error. - No sorting or manipulation around the boundary due to randomization of treatment.\n\n**Statistical Assumptions:**\n\nBecause this is a randomized experiment, the assumptions are:\n\n*Randomized validity*\n\nThe author reports no evidence of imbalance across the treatment and control groups Our California-only replication relies on the same randomization. Randomization was implemented through the Qualtrics platform, ensuring that map exposure was independent of respondent characteristics.\n\n*SUTVA*\n\nRespondents complete surveys individually and therefore cannot see each others maps Spillovers are unlikely due to the online setting Due to this, we believe that statistical assumptions are reasonable. Although all treated individuals received a map, the variation in treatment was their homes location relative to the flood zone.\n\n**Sampling and External Validity:**\n\n-   The sample are the California respondents that were recruited via \"address-matched mail-to-web sampling\"\n\n-   This generalizes respondents that are Californian (more likely climate aware), metropolitan and more likely to engage with mailed surveys\n\n-   Even inside the flood zone, respondents show low personal concern\n\n-   These results may not generalize other people that are: Renters Low-income People that dont respond to mail surveys Other states or countries\n\n-   Our replication focuses on California which is more climate-concerned than the national-average Because of this, we find external validity is weak and may not be able to be generalized to the broader population.\n\nTherefore, due to the relatively small sample size and the geographic limit of only one coastal community, it can be concluded that these results can only be generalized to the residents of the San Francisco Bay Area, California.\n\n**Outcome Validity Concerns:**\n\nThe outcome can be a concern as a single 4-point Likert item asking how much sea level rise will harm them personally raises some issues. The paper mentions respondents spent a median time of 33 seconds on the map page which may introduce a reaction that does not internalize the information fully The lower scores may reflect reassurance (they are not in the flood zone) or disbelief in the map Treatment Validity Concerns\n\nA map of sea level rise shown once at the discretion of the respondents may not capture the full opinion of the respondent. 19% of the respondents found the map not very or not at all credible. We can say that the Measurement validity is decent, however maybe limited in measuring risk perception.\n\n**Other Limitations:**\n\n*Spillover effect*\n\nIt would not have been possible for the researchers to control whether or not residents discussed the surveys and their responses with each other. This could lead to observations that are not truly independent.\n\n*Time lag*\n\nDifferences in response time (or even allowing for a long response time) could potential skew outcomes. For example, if there was a weather event that led to minor flooding in the time period that the survey was open, respondents who completed the survey before and after the event could be basing their beliefs off of different realities (and not off of the treatment). These discrepancies were not controlled for in the study methods.\n\nOverall, our California‑only replication supports the paper’s core experimental finding: randomized exposure to personalized SLR maps causally reduces reported personal concern about sea‑level rise. The internal validity of this estimate is strong due to proper randomization, minimal risk of spillovers. However, the broader policy relevance of this effect is limited. The outcome measure uses coarse scores and maybe be sensitive to short‑run reactions, the treatment is a one‑time map rather than the standard policy communication, and the California/San Francisco sample may and probably is unrepresentative of the broader population. These factors weaken external validity and can raise questions about whether the observed “backfire effect”. In all, the experiment credibly identifies a short‑run causal effect in this specific survey context, but the evidence is less convincing as support for the stronger policy claim that SLR maps broadly reduce public concern in real‑world settings.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/core-js-2.5.3/shim.min.js\"></script>\n<script src=\"../../site_libs/react-18.2.0/react.min.js\"></script>\n<script src=\"../../site_libs/react-18.2.0/react-dom.min.js\"></script>\n<script src=\"../../site_libs/reactwidget-2.0.0/react-tools.js\"></script>\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/reactable-0.4.4/reactable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/reactable-binding-0.4.4/reactable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}